import { mkdir, writeFile, rm, copyFile, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { products, site } from '../src/site-data.mjs';
import { services } from '../src/guides.mjs';
import { servicePages } from '../src/service-pages.mjs';
import { categories } from '../src/categories.mjs';
import { decorate, sitemap, origin, previewMode } from '../src/seo.mjs';
const root = fileURLToPath(new URL('../', import.meta.url));
const out = resolve(root, 'dist');
// dist contains generated output only. Rebuild cleanly so withdrawn candidates cannot remain accessible.
await rm(out, {recursive:true, force:true});
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pagePaths = [];
async function save(path, content) { if(path.endsWith('.html')) { const route = '/' + path.replace(/index\.html$/, ''); pagePaths.push(route); content = decorate(content,route); } const dest = resolve(out, path); await mkdir(dirname(dest), {recursive:true}); await writeFile(dest, content); }
const placeholder = (name, large=false) => `<div class="photo-placeholder ${large?'large':''}" role="img" aria-label="Verified product image pending for ${esc(name)}"><span class="photo-symbol" aria-hidden="true">＋</span><span>PRODUCT IMAGE PENDING</span><small>${esc(name)}</small></div>`;
const productImage = (p, large=false) => {
  if(!p.image) return placeholder(p.name,large);
  const {src,alt,width,height}=p.image;
  if(!/^\/images\/[a-zA-Z0-9/_-]+\.(jpg|jpeg|png|webp|avif)$/.test(src) || !alt || !(width>0 && height>0)) throw new Error('Invalid product image metadata: '+p.id);
  return `<div class="product-photo ${large?'large':''}"><img src="${esc(src)}" alt="${esc(alt)}" width="${width}" height="${height}" loading="${large?'eager':'lazy'}" decoding="async"></div>`;
};
const productGallery = p => {
  const photos = p.gallery || [];
  if (!photos.length) return productImage(p,true);
  return `<div class="product-gallery" aria-label="${esc(p.name)} product images">${photos.map((photo,index)=>`<figure>${productImage({...p,image:photo},index===0)}<figcaption>${esc(photo.caption || `${p.name} — view ${index+1}`)}</figcaption></figure>`).join('')}</div>`;
};
const card = p => `<article class="product-card">${productImage(p)}<div class="card-body"><span class="eyebrow">SPEAKER SHORTLIST</span><h3><a href="/products/${p.id}/">${esc(p.name)} <span aria-hidden="true">→</span></a></h3><p>${esc(p.status)}</p><a class="text-link" href="/inquiry/?product=${p.id}">Add to an enquiry <span aria-hidden="true">→</span></a></div></article>`;
const navigation = (current, className) => `<nav class="${className}" aria-label="Main navigation">${[['Home','/','home'],['Products','/products/','products'],['OEM/ODM','/services/oem-odm/','services'],['About Us','/about/','about'],['Contact','/contact/','contact']].map(([name,href,key])=>`<a ${current===key?'aria-current="page"':''} href="${href}">${name}</a>`).join('')}</nav>`;
const categoryCards = categories.map((c,i)=>`<a class="category-card" href="/products/type/${c.id}/"><span class="eyebrow">0${i+1} / BROWSE BY STYLE</span><h3>${c.name} <span aria-hidden="true">→</span></h3><p>${c.description}</p></a>`).join('');
const layout = (title, body, current='home') => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="SpeakerB2B wholesale speaker sourcing and custom branding enquiry draft."><title>${esc(title)} | ${site.name}</title><link rel="stylesheet" href="/styles.css"><script src="/inquiry.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><div class="draft-bar">WORKING PREVIEW <span>Product details are being verified · Enquiries are not sent</span></div><header><a class="logo" href="/" aria-label="SpeakerB2B home"><span class="logo-icon" aria-hidden="true">≋</span>speaker<span>b2b</span><i>.</i></a>${navigation(current, 'desktop-nav')}<details class="mobile-menu"><summary>Menu <span aria-hidden="true">＋</span></summary>${navigation(current, 'mobile-nav')}</details></header><main id="main" tabindex="-1">${body}</main><footer><div><a class="logo" href="/">speaker<span>b2b</span><i>.</i></a><p>Sound starts with the right conversation.</p></div><div><a href="/products/">Explore speakers</a><a href="/services/wholesale/">Wholesale sourcing</a><a href="/services/oem-odm/">OEM / ODM enquiries</a><a href="/about/">About Us</a><a href="/contact/">Contact</a></div><div><span class="eyebrow">PRE-LAUNCH DRAFT</span><p>Intended website: ${site.intendedDomain}<br>Business and contact details pending.</p></div></footer></body></html>`;
const serviceCards = services.map((s,i)=>`<article class="service-card"><span class="step">0${i+1}</span><h3>${s.title}</h3><p>${s.text}</p><a class="text-link" href="${s.href}">Explore this service →</a></article>`).join('');
await save('index.html',layout('Speakers for your next business idea',`<section class="hero"><div class="hero-copy"><p class="eyebrow">BLUETOOTH SPEAKERS FOR BUSINESS</p><h1>Wholesale speakers.<br><em>Start your next range.</em></h1><p class="intro">Explore our model shortlist and prepare a focused wholesale or custom-branding brief for your business.</p><div class="actions"><a class="button" href="/products/">Browse speakers <span aria-hidden="true">→</span></a><a class="button secondary" href="/services/oem-odm/">OEM / ODM enquiries →</a></div><p class="hero-note">For retailers, distributors and branded merchandise teams.</p></div><div class="hero-panel"><span class="eyebrow">SOURCE. BRAND. MAKE IT YOURS.</span><div class="outdoor-art" aria-hidden="true"><i></i><i></i><i></i><i></i></div><div class="panel-bottom"><h2>A focused range.<br>A considered brief.</h2><p>Product photography coming after verification.</p></div></div></section><section class="audience-strip"><span>RETAIL & DISTRIBUTION</span><span>BRAND MERCHANDISE</span><span>BUSINESS SOURCING</span></section><section class="section"><p class="eyebrow">FIND YOUR STARTING POINT</p><h2>Explore by type.</h2><div class="category-grid">${categoryCards}</div></section><section class="section compact"><div class="section-heading"><div><p class="eyebrow">A STARTING POINT FOR YOUR SEARCH</p><h2>A starting model for your next brief.</h2></div><a class="text-link" href="/products/">View all ${products.length} candidates →</a></div><div class="product-grid">${products.slice(0,4).map(card).join('')}</div><p class="note">Candidate names are shown for discussion. Specifications, availability and model relationships remain under review.</p></section><section class="section service-section"><p class="eyebrow">FROM SHORTLIST TO SOURCING BRIEF</p><h2>Start with what you need.</h2><div class="service-grid">${serviceCards}</div></section><section class="cta"><div><p class="eyebrow">LET’S SHAPE THE BRIEF</p><h2>A model in mind?<br>Put your requirements together.</h2></div><a class="button light" href="/inquiry/">Prepare an enquiry →</a></section>`));
await save('products/index.html',layout('Speaker shortlist',`<section class="page-heading"><p class="eyebrow">EXPLORE / SPEAKERS</p><h1>A sound starting point.</h1><p class="intro">Compare model candidates for your next sourcing conversation. Verified photography and specifications will be added after review.</p></section><section class="section compact"><nav class="category-tabs" aria-label="Product categories"><a href="/products/" aria-current="page">All models</a>${categories.map(c=>`<a href="/products/type/${c.id}/">${c.name}</a>`).join('')}</nav><div class="catalog-label"><strong>${products.length} model candidates</strong><span>Specifications under review</span></div><div class="product-grid">${products.map(card).join('')}</div><p class="note">Only the eight reviewed model names appear here. Unconfirmed aliases and unnamed models remain outside this catalog. Listing does not confirm stock or customization availability.</p></section>`,'products'));
for (const p of products) await save(`products/${p.id}/index.html`,layout(p.name,`<section class="section detail"><div><a class="text-link" href="/products/">← All speakers</a>${productGallery(p)}</div><div class="detail-copy"><p class="eyebrow">SPEAKER MODEL CANDIDATE</p><h1>${esc(p.detailTitle || p.name)}</h1><p class="intro">${esc(p.description)}</p><div class="product-types" aria-label="Product browsing groups">${categories.filter(c=>c.models.includes(p.id)).map(c=>`<a href="/products/type/${c.id}/">${c.name}</a>`).join('')}</div><span class="status-pill">Details under review</span><p>Use this model as a starting point for an enquiry. Product identity, specifications and branding options will be confirmed before quotation.</p><dl><div><dt>Product photography</dt><dd>${p.image ? 'Supplier-provided product image' : 'Awaiting verified images'}</dd></div>${p.specifications ? p.specifications.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('') : '<div><dt>Technical specifications</dt><dd>Awaiting verification</dd></div>'}${p.wholesalePrice ? `<div><dt>Wholesale Price</dt><dd>${esc(p.wholesalePrice)}</dd></div><div><dt>Order quantity</dt><dd>To be confirmed</dd></div>` : '<div><dt>Price & order quantity</dt><dd>To be confirmed in quotation</dd></div>'}<div><dt>Availability & delivery</dt><dd>Confirmation required</dd></div></dl>${p.specificationNote ? `<p class="note">${esc(p.specificationNote)}</p>` : ''}<a class="button" href="/inquiry/?product=${p.id}">Prepare an enquiry for ${esc(p.name)} →</a><p class="note">The enquiry brief stays in your browser. Sending is not enabled in this preview.</p></div></section><section class="section service-section"><p class="eyebrow">MAKE YOUR BRIEF USEFUL</p><h2>Tell us the context.</h2><div class="service-grid"><article><h3>Your quantity</h3><p>Share an estimated order size. Minimum quantities have not been confirmed.</p></article><article><h3>Your market</h3><p>Include the destination and any required technical or compliance documentation.</p></article><article><h3>Your branding</h3><p>Describe your logo and packaging needs so feasibility can be checked.</p></article></div></section>`,'products'));
await save('services/index.html',layout('Sourcing & branding',`<section class="page-heading"><p class="eyebrow">SOURCING & BRANDING</p><h1>From a model<br>to your requirements.</h1><p class="intro">Build a brief for standard products or a custom branding project. Each request begins with checking the details.</p></section><section class="section compact"><div class="service-grid">${serviceCards}</div><div class="callout"><h2>Looking for available stock?</h2><p>Current inventory is not confirmed on this draft. Include your quantity, destination and target date in the brief so availability can be checked before a quotation.</p></div></section><section class="section service-section"><p class="eyebrow">THE PLANNED ENQUIRY PROCESS</p><h2>Clear information at every step.</h2><ol class="process"><li><h3>Choose a candidate</h3><p>Pick a model or describe what you are looking for.</p></li><li><h3>Prepare your requirements</h3><p>Include quantity, market, branding and timing.</p></li><li><h3>Confirm before ordering</h3><p>Product details, pricing and delivery need a reviewed quotation. This preview does not send requests.</p></li></ol><a class="button" href="/inquiry/">Build your brief →</a></section>`,''));
await save('inquiry/index.html',layout('Prepare an enquiry',`<section class="page-heading"><p class="eyebrow">YOUR NEXT STEP</p><h1>Let’s get the brief right.</h1><p class="intro">Put your sourcing requirements in one place.</p></section><section class="section inquiry-layout compact"><aside><h2>Prepare now.<br>Send later.</h2><p>This is a draft enquiry builder. There is no connected recipient or submission service yet.</p><p>Your entries stay on this page and are not saved or sent. Copy or download the generated brief before leaving.</p><p class="note">Do not enter confidential information into this preview.</p></aside><form id="inquiry-form"><div class="form-banner">Preview only — nothing will be sent.</div><label>Product<select name="product"><option value="">General enquiry / help me choose</option>${products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><input type="hidden" name="productUrl"><label>Enquiry type<select name="intent"><option value="general">General sourcing enquiry</option><option value="wholesale">Wholesale / stock enquiry</option><option value="oem-odm">OEM / ODM enquiry</option></select></label><div class="form-grid"><label>Company<input name="company" autocomplete="organization" required maxlength="120"></label><label>Work email<input name="email" type="email" autocomplete="email" required maxlength="254"></label><label>Estimated quantity <span>(optional)</span><input name="quantity" placeholder="e.g. 500 units" maxlength="80"></label><label>Destination market<input name="destination" autocomplete="country-name" required maxlength="120"></label></div><label>Your requirements<textarea name="requirements" rows="5" required maxlength="4000" placeholder="Branding, packaging, target date, required documentation…"></textarea></label><button class="button" type="submit" disabled>Generate my brief <span aria-hidden="true">→</span></button><p id="form-status" role="status" aria-live="polite"></p><div id="brief-result" hidden><label>Your brief — keep for your records<textarea id="brief" rows="12" readonly></textarea></label><div class="actions"><button class="button" id="copy-brief" type="button">Copy brief</button><button class="button secondary" id="download-brief" type="button">Download .txt</button></div><p id="export-status" role="status" aria-live="polite"></p></div><noscript><p>JavaScript is required to generate a brief. Sending is not available.</p></noscript></form></section>`,'inquiry'));
for (const s of servicePages) await save(`services/${s.path}/index.html`,layout(s.title,`<section class="page-heading"><a class="text-link" href="/services/">← All services</a><p class="eyebrow service-eyebrow">${s.eyebrow}</p><h1>${s.headline}</h1><p class="intro">${s.intro}</p></section><section class="section compact"><div class="service-grid">${s.steps.map(([title,text],i)=>`<article class="service-card"><span class="step">0${i+1}</span><h2 class="service-step-title">${title}</h2><p>${text}</p></article>`).join('')}</div><div class="callout"><h2>${s.noteTitle}</h2><p>${s.note}</p></div></section><section class="cta"><div><p class="eyebrow">YOUR REQUIREMENTS, IN ONE PLACE</p><h2>Make a clear starting brief.</h2><p class="cta-note">Preview only: your brief stays on this page until you copy it.</p></div><a class="button light" href="/inquiry/?intent=${s.intent}">${s.action} →</a></section>`,s.path==='oem-odm'?'services':''));
for (const c of categories) await save(`products/type/${c.id}/index.html`,layout(c.name,`<section class="page-heading"><a class="text-link" href="/products/">← All speakers</a><p class="eyebrow service-eyebrow">BROWSE BY TYPE</p><h1>${c.name}</h1><p class="intro">${c.description}</p></section><section class="section compact"><nav class="category-tabs" aria-label="Product categories"><a href="/products/">All models</a>${categories.map(x=>`<a ${x.id===c.id?'aria-current="page"':''} href="/products/type/${x.id}/">${x.name}</a>`).join('')}</nav><div class="product-grid">${products.filter(p=>c.models.includes(p.id)).map(card).join('')}</div><p class="note">A model may appear in more than one browsing group. Specifications and availability are not confirmed by a category label.</p></section>`,'products'));
await save('about/index.html',layout('About Us',`<section class="page-heading"><p class="eyebrow">ABOUT SPEAKERB2B</p><h1>Speakers for your business.<br>A clear place to start.</h1><p class="intro">SpeakerB2B is a wholesale speaker sourcing and customization enquiry project for business buyers.</p></section><section class="section compact"><div class="service-grid"><article class="service-card"><span class="step">01</span><h2 class="service-step-title">Find a starting model</h2><p>Explore a focused shortlist of speaker models for your retail, distribution or branded merchandise brief.</p></article><article class="service-card"><span class="step">02</span><h2 class="service-step-title">Explain your requirements</h2><p>Share your intended market, quantities and branding needs. Product and customization details need to be checked for your project.</p></article><article class="service-card"><span class="step">03</span><h2 class="service-step-title">Confirm the details</h2><p>Technical specifications, stock, pricing and delivery must be confirmed before you make an order decision.</p></article></div><div class="callout"><h2>A catalog in progress.</h2><p>We are preparing the product photography and verified information for this website. Business contact details and a connected enquiry service are not yet available in this preview.</p></div></section><section class="cta"><div><p class="eyebrow">START WITH YOUR REQUIREMENTS</p><h2>Let’s shape your speaker brief.</h2></div><a class="button light" href="/inquiry/">Prepare an enquiry →</a></section>`,'about'));
await save('contact/index.html',layout('Contact',`<section class="page-heading"><p class="eyebrow">CONTACT SPEAKERB2B</p><h1>Your next sourcing conversation<br>starts with a clear brief.</h1><p class="intro">For wholesale, branding or product development enquiries, prepare your requirements using the draft builder.</p></section><section class="section compact inquiry-layout"><div><h2>Contact details</h2><dl><div><dt>Email</dt><dd>Not configured yet</dd></div><div><dt>Phone / WhatsApp</dt><dd>Not configured yet</dd></div><div><dt>Business address</dt><dd>Awaiting confirmation</dd></div></dl><p class="note">No live contact channel is connected in this preview.</p></div><div class="callout contact-callout"><p class="eyebrow">PREPARE NOW · SEND LATER</p><h2>Keep your enquiry ready.</h2><p>Select a model, describe your requirements and generate a brief you can copy. Nothing is sent or stored by the draft builder.</p><a class="button" href="/inquiry/">Build an enquiry →</a><p class="note">When an approved contact channel is configured, this page will be updated.</p></div></section>`,'contact'));
await save('404.html',layout('Page not found','<section class="page-heading"><h1>That page is not here.</h1><a class="button" href="/products/">Explore speakers</a></section>',''));
await save('sitemap.xml',sitemap(pagePaths));
await save('robots.txt',previewMode?'User-agent: *\nDisallow: /\n':`User-agent: *\nAllow: /\nDisallow: /inquiry/\nSitemap: ${origin}/sitemap.xml\n`);
await save('_headers',`/*\n${previewMode?'  X-Robots-Tag: noindex, nofollow\n':''}  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n`);
await writeFile(resolve(root,'public/products.json'),JSON.stringify(products,null,2)+'\n');
for (const [source,target] of [['src/styles.css','styles.css'],['public/inquiry.js','inquiry.js'],['public/products.json','products.json']]) await copyFile(resolve(root,source),resolve(out,target));
try { await cp(resolve(root,'public/images'),resolve(out,'images'),{recursive:true}); } catch(error) { if(error.code!=='ENOENT')throw error; }
console.log(`Built ${products.length} model pages and 12 general/category pages into ${out}`);
