import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir, stat } from 'node:fs/promises';
import { resolve } from 'node:path';
import { products, site } from '../src/site-data.mjs';
import { decorate, breadcrumbs, origin } from '../src/seo.mjs';
const root = new URL('../dist/', import.meta.url);
async function files(dir) { let result=[]; for(const e of await readdir(dir,{withFileTypes:true})) { const path=new URL(e.name+(e.isDirectory()?'/':''),dir); result.push(...(e.isDirectory()?await files(path):[path])); } return result; }
test('All candidate identities remain distinct and excluded model is absent',()=>{assert.equal(products.length,8); assert.equal(new Set(products.map(p=>p.id)).size,8); for(const id of ['s12','s11','x2pro','s16','s20','gb01','gb03','mg-ii']) assert.ok(products.some(p=>p.id===id)); for (const id of ['tt-sk027','a8-pro','s12-2','s11-1','digital-display-rgb']) assert.ok(!products.some(p=>p.id===id));});
test('Every internal page and asset link resolves in the build',async()=>{for(const f of await files(root)){if(!f.pathname.endsWith('.html'))continue;const html=await readFile(f,'utf8');for(const match of html.matchAll(/(?:href|src)="([^"#]+)"/g)){const url=new URL(match[1],'https://local.test');assert.equal(url.origin,'https://local.test');const path=decodeURIComponent(url.pathname);await stat(new URL('.'+path+(path.endsWith('/')?'index.html':''),root));}assert.match(html, /name="viewport"/);assert.match(html,/noindex,nofollow/);assert.match(html, /lang="en"/);}});
test('Draft contains no old-site content, claims or hidden verification metadata',async()=>{for(const f of await files(root)){const s=await readFile(f,'utf8');assert.doesNotMatch(s,/Manike|TaoTronics|MIEVHub|productLink|20W|15W|12W|free shipping|in stock|guaranteed|google-analytics|gtag\(/i);}await assert.rejects(stat(new URL('verification.json',root)));});
test('Enquiry creates a local brief with one consistent productUrl field',async()=>{const js=await readFile(new URL('inquiry.js',root),'utf8');const html=await readFile(new URL('inquiry/index.html',root),'utf8');assert.match(js,/preventDefault/);assert.match(html,/name="productUrl"/);assert.doesNotMatch(js,/fetch\(|XMLHttpRequest|sendBeacon|localStorage/);assert.doesNotMatch(html,/<form[^>]+action=/);assert.match(js,/Nothing has been sent/);});
test('All pages have unique SEO metadata, one H1, and descriptive breadcrumbs',async()=>{const titles=new Set(),descriptions=new Set();let pages=0;for(const f of await files(root)){if(!f.pathname.endsWith('.html'))continue;const html=await readFile(f,'utf8');const title=html.match(/<title>(.*?)<\/title>/)[1];const description=html.match(/name="description" content="([^"]+)"/)[1];assert.ok(!titles.has(title),title);assert.ok(!descriptions.has(description),description);titles.add(title);descriptions.add(description);assert.equal([...html.matchAll(/<h1[ >]/g)].length,1);assert.ok(description.length>60&&description.length<220);assert.doesNotMatch(html,/<link rel="canonical"/);if(f.pathname!==new URL('index.html',root).pathname)assert.match(html,/aria-label="Breadcrumb"/);pages++;}assert.equal(pages,20);});
test('Sitemap lists real canonical routes and draft robots block indexing',async()=>{const sitemap=await readFile(new URL('sitemap.xml',root),'utf8');const routes=[...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map(x=>x[1]);assert.equal(routes.length,18);assert.equal(new Set(routes).size,routes.length);for(const route of routes){assert.ok(route.startsWith(origin+'/'));const path=new URL(route).pathname;await stat(new URL('.'+path+'index.html',root));}assert.match(await readFile(new URL('robots.txt',root),'utf8'),/Disallow: \/\n/);assert.match(await readFile(new URL('_headers',root),'utf8'),/X-Robots-Tag: noindex/);});
test('Production SEO switch changes only metadata and preserves enquiry noindex',()=>{const template='<head><title>x</title><meta name="description" content="x"><meta name="robots" content="noindex,nofollow"></head><main id="main"></main>';const publicHtml=decorate(template,'/products/s16/',false);assert.match(publicHtml,/content="index,follow"/);assert.match(publicHtml,/rel="canonical" href="https:\/\/speakerb2b.com\/products\/s16\/"/);assert.match(decorate(template,'/inquiry/',false),/content="noindex,nofollow"/);assert.deepEqual(breadcrumbs('/products/s16/').map(x=>x.name),['Home','Products','S16']);assert.doesNotMatch(publicHtml,/"@type":"(?:Product|Review|AggregateRating|Offer)"/);});
test('Frontend stays small and independent of external assets',async()=>{assert.ok((await stat(new URL('inquiry.js',root))).size<10000);assert.ok((await stat(new URL('styles.css',root))).size<30000);const css=await readFile(new URL('styles.css',root),'utf8');assert.doesNotMatch(css,/@import|https?:\/\//);});

test('Contact delivery remains disabled and no email address is published',async()=>{assert.equal(site.inquiryEnabled,false);for(const f of await files(root)){assert.doesNotMatch(await readFile(f,'utf8'),/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}|mailto:|formaction=/i);}});
